[theme]
primaryColor             = "#0984e3"
backgroundColor          = "#f5f7fa"
secondaryBackgroundColor = "#ffffff"
textColor                = "#2d3436"
font                     = "sans serif"

[server]
headless = true
